### ISSUE TITLE
Further sandwiches 

### ISSUE THREAD

**Issue by raptor4916** [PrecociouslyDigital/sandwich-definitions#10]
Suppose I would take a whole roast chicken and slap it between 2 loaves of bread is that a sandwich? It feels like one becuase a whole roast chicken is multiple types of meat dark meat white meat and the back meat are all different in physical composition and flavor to be considered different types of meat under the lemma

**Comment by PrecociouslyDigital** [comment]
Technically Yes.

I don't like it.
